[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube

; 1. Esegui lo script prima della compilazione
extra_scripts = pre:add_hardfloat.py

build_flags = 
    -D USE_HAL_DRIVER
    -D STM32G474xx
    ; 2. Linka la libreria DSP Hard-Float (lf = L-series/M4 Hard Float)
    -larm_cortexM4lf_math
    -I lib/FreeRTOS/Source/include
    -I lib/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -I include
build_src_filter = 
    +<*>
    +<../lib/FreeRTOS/Source/*.c>
    +<../lib/FreeRTOS/Source/portable/GCC/ARM_CM4F/*.c>
    +<../lib/FreeRTOS/Source/portable/MemMang/heap_4.c>

lib_deps = 
    Util-Fonts

monitor_speed = 115200